### ISSUE TITLE
KONTENA GUEST - GUEST SERVICE - Memesan Room Service yang tidak ada price

### ISSUE THREAD

**Issue by agilma** [ThunderID/KONTENA-MAINTENANCE#10]
**Tuliskan Error/Bug**
Memesan Room Service gagal dan mendapatkan pesan Error "tidak dapat terhubung dengan server" dan item di cart tidak berkurang setelah mendapatkan error tersebut.

**Platform / Aplikasi yang bermasalah:**
Kontena Guest

**Langkah-langkah error terjadi**
pertama saya memesan beberapa room service lalu saya pesan mendapatkan error tersebut, lalu saya kurangkan total item dicart tidak berkurang, (seperti digambar)

**Screenshots**
![Screenshot_20200215-085412](https://user-images.githubusercontent.com/4099329/74580157-97b2e980-4fd3-11ea-9cad-1a7ca2221a29.png)
![Screenshot_20200215-085423](https://user-images.githubusercontent.com/4099329/74580159-9aadda00-4fd3-11ea-9aca-02ea6d0bf318.png)
![Screenshot_20200215-085433](https://user-images.githubusercontent.com/4099329/74580162-9d103400-4fd3-11ea-8683-f19821797f59.png)

**Jenis HP (khusus untuk mobile apps):**
 - Device: Google Pixel 2
 - OS: Android 10

**Catatan**
Mungkin ini terjadi karena item room service tidak memiliki price, karena waktu saya menambahkan item room service yang terdapat pricenya, berjalan lancar.

**Comment by budi7** [comment]
Fixed on live @chelsymooy
