### ISSUE TITLE
KONTENA GUEST - GUEST SERVICE - Status pesanan tidak berubah

### ISSUE THREAD

**Issue by agilma** [ThunderID/KONTENA-MAINTENANCE#11]
**Tuliskan Error/Bug**
Status pesanan guest service tidak berubah, ketika pesanan dicancel oleh pihak OT

**Platform / Aplikasi yang bermasalah:**
Kontena Guest

**Langkah-langkah error terjadi**
Pesan Guest Service, lalu dari pihak HK - OT ngecancel pesanan

**Screenshots**
Jika memungkinkan, lampirkan screenshot permasalahan Anda
**pesanan status masih diterima**
![Screenshot_20200215-101636](https://user-images.githubusercontent.com/4099329/74581073-a8685d00-4fdd-11ea-95a8-816f91b45842.png)
**detail pesanan**
![Screenshot_20200215-100233](https://user-images.githubusercontent.com/4099329/74581084-c209a480-4fdd-11ea-9735-1b6cb4688b00.png)

**Jenis HP (khusus untuk mobile apps):**
 - Device: Google Pixel 2
 - OS: Android 10

**Comment by budi7** [comment]
fixed at https://github.com/budi7/kontena/releases/tag/1.2.1
