### ISSUE TITLE
KONTENA GUEST - HOME/ARTIKEL - GAMBAR TIDAK TAMPIL

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/KONTENA-MAINTENANCE#13]
**Tuliskan Error/Bug**
gambar artikel tidak muncul

**Platform / Aplikasi yang bermasalah:**
KONTENA GUEST

**Screenshots**
![WhatsApp Image 2020-02-15 at 9 29 57 PM](https://user-images.githubusercontent.com/5895063/74589748-9072f680-503a-11ea-9363-d17927d8c0b9.jpeg)

 
**Jenis HP (khusus untuk mobile apps):**
 - Redmi 5, Oreo

**Comment by chelsymooy** [comment]
Sudah muncul Hari ini

**Comment by budi7** [comment]
![image](https://user-images.githubusercontent.com/10555410/74643291-0f853d80-51a7-11ea-809a-4da24cc4ac21.png)

potential problem, filename extension

**Comment by budi7** [comment]
another potential problem: client's network
