### ISSUE TITLE
KONTENA GUEST - Token expired tidak diperbaharui

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/KONTENA-MAINTENANCE#14]
**Tuliskan Error/Bug**
Setelah lama tidak login, trus apps nya dibuka. Fitur tidak berfungsi

**Platform / Aplikasi yang bermasalah:**
Kontena Tamu

**Screenshots**
![Screenshot_2020-02-16-10-26-40-407_com whatsapp](https://user-images.githubusercontent.com/5895063/74598610-d6fe3a80-50a6-11ea-855c-cf5baee9c4fd.jpg)

**Jenis HP (khusus untuk mobile apps):**
 Semua platform

**Catatan**
Apakah memungkinkan kalau error unauthorized, langsung dilempar ke halaman login

**Comment by budi7** [comment]
updated at https://github.com/budi7/kontena/releases/tag/1.2.1
