### ISSUE TITLE
KONTENA GUEST - Tidak bisa request password

### ISSUE THREAD

**Issue by agilma** [ThunderID/KONTENA-MAINTENANCE#16]
**Tuliskan Error/Bug**
tidak bisa request password utk apps Kontena Tamu yang versi Test

**Platform / Aplikasi yang bermasalah:**
Kontena Guest versi Test

**Screenshots**
![Screenshot_20200216-111416](https://drive.google.com/uc?export=view&id=1A78JS1-rs_1Mq2UZaLBuELWlsfrtylbE)

**Jenis HP (khusus untuk mobile apps):**
 - Device: Google Pixel 2
 - OS: Android 10
 - Version Apps 1.2.0

**Comment by chelsymooy** [comment]
Coba test di live
be wise, setiap testing sms kena charge

**Comment by budi7** [comment]
tested by @chelsymooy
