### ISSUE TITLE
API - Inconsistent Expired JWT Handler

### ISSUE THREAD

**Issue by budi7** [ThunderID/KONTENA-MAINTENANCE#19]
**Tuliskan Error/Bug**
Pada beberapa kasus, JWt yang expired akan direturn error 500 dari APi dengan error message Unauthorized, pada kasus yang lain, masih di return 200 dengan error validation : JWT expired 

**Platform / Aplikasi yang bermasalah:**
API - LIVE

**Screenshots**
![image](https://user-images.githubusercontent.com/10555410/74701329-fb8a1c00-5238-11ea-9144-104bccdbb43d.png)

**Expectation**
return error 500 dengan error message Unauthorized instead

**Comment by chelsymooy** [comment]
ada screenshot headernya kah?
