### ISSUE TITLE
KONTENA GUEST - GUEST SERVICE - Request Assistance / Butuh Bantuan bisa tambah note

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/KONTENA-MAINTENANCE#4]
**Apakah fitur ini dibutuhkan karena ada permasalahan dalam sistem? Ceritakan tentang permasalahan Anda**
Ingin menambahkan note pada guest service [Bisa menuliskan item]

**Catatan tambahan dari API**
1. Yang bisa menambahkan note hanya RoomItem yg memiliki attribute "is_custom" bernilai true
2. Disimpan ke field "note" di StoreRoomService -> lines

**Comment by chelsymooy** [comment]
sample query 1

query room_item{
  RoomItems{
    data{
      name
      is_custom
    }
  }
}

**Comment by chelsymooy** [comment]
query sample 1

mutation room_service{
  StoreRoomService(reception_id:16 room_id:10 user_id:1 lines:[
    {room_item_id:2885 qty:1 note:"PINJAM SENDOK"}
  ] description:{delivery_location:"POOL" payment_method:"CASH" payment_amount:0}) {
    id
    description{
      delivery_location
      payment_method
      payment_amount
    }
  }
}

**Comment by chelsymooy** [comment]
TEST LOCATION

http://128.199.145.173:9888/graphiql

ACTIVE STAY

username: 6281333517875	
password: 123123123

**Comment by budi7** [comment]
policy: item "Lainnya" only 

updated at https://github.com/budi7/kontena/releases/tag/1.2.1
