### ISSUE TITLE
KONTENA GUEST - ROOM SERVICE - Room service bisa tambah note

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/KONTENA-MAINTENANCE#5]
**Apakah fitur ini dibutuhkan karena ada permasalahan dalam sistem? Ceritakan tentang permasalahan Anda**
Saya tidak bisa menuliskan preferensi makanan saya

**Jelaskan solusi yang Anda harapkan**
Saya ingin menambahkan note untuk preferensi makanan saya (misal: pedas, tidak pakai polong, dll)

**Catatan tambahan dari API**
1. Note untuk semua produk hanya berlaku di Room Service alias Restaurant

**Comment by chelsymooy** [comment]
query sample 1

mutation room_service{
  StoreRoomService(reception_id:16 room_id:10 user_id:1 pos_point_id:1 lines:[
    {pos_product_id:1 qty:1 note:"LESS SUGAR"}
  ] description:{delivery_location:"POOL" payment_method:"CASH" payment_amount:20000}) {
    id
    description{
      delivery_location
      payment_method
      payment_amount
    }
  }
}

**Comment by chelsymooy** [comment]
TEST LOCATION

http://128.199.145.173:9888/graphiql

ACTIVE STAY

username: 6281333517875	
password: 123123123

**Comment by budi7** [comment]
https://github.com/budi7/kontena/releases/tag/1.2.1
