### ISSUE TITLE
KONTENA GUEST - ROOM SERVICE - bisa catat lokasi pengantaran, dan payment referensi

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/KONTENA-MAINTENANCE#6]
**Apakah fitur ini dibutuhkan karena ada permasalahan dalam sistem? Ceritakan tentang permasalahan Anda**
1. Saya ingin tamu bisa pesan makanan dari public area, misal kolam renang
2. Saya ingin waitress cukup sekali jalan untuk menyelesaikan order layanan kamar
 
**Jelaskan solusi yang Anda harapkan**
1. Tamu bisa menulis lokasi pengantaran mereka
2. Tamu juga bisa menulis metode pembayaran yang mereka harapkan 
dan nominal pembayarannya, jika menggunakan cash

**Catatan tambahan dari API**
1. Metode pembayaran yang diijinkan diambil dari type Stay -> open_payment_method
2. Untuk simpan lokasi pengantaran, metode pembayaran dan nominal pembayaran bisa menggunakan field "description" di mutasi StoreRoomService
3. Untuk baca lokasi pengantaran, metode pembayaran dan nominal pembayaran bisa menggunakan field "description" di type RoomService

**Comment by chelsymooy** [comment]
Sample query 1


query open_payment_method{
  Stays(is_active:true limit:1){
    data{
      open_payment_method
    }
  }
}

**Comment by chelsymooy** [comment]
Sample query 2 & 3

mutation room_service{
  StoreRoomService(reception_id:16 room_id:10 user_id:1 pos_point_id:1 lines:[
    {pos_product_id:1 qty:1}
  ] description:{delivery_location:"POOL" payment_method:"CASH" payment_amount:20000}) {
    id
    description{
      delivery_location
      payment_method
      payment_amount
    }
  }
}

**Comment by chelsymooy** [comment]
TEST LOCATION

http://128.199.145.173:9888/graphiql

ACTIVE STAY

username: 6281333517875	
password: 123123123

**Comment by budi7** [comment]
updated at https://github.com/budi7/kontena/releases/tag/1.2.1
