### ISSUE TITLE
KONTENA GUEST - GUEST SERVICE - bisa catat lokasi pengantaran

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/KONTENA-MAINTENANCE#8]
**Apakah fitur ini dibutuhkan karena ada permasalahan dalam sistem? Ceritakan tentang permasalahan Anda**
1. Saya ingin tamu bisa pesan layanan dari public area, misal pesan handuk di kolam renang
 
**Jelaskan solusi yang Anda harapkan**
1. Tamu bisa menulis lokasi pengantaran mereka

**Catatan tambahan dari API**
1. Untuk simpan lokasi pengantaran menggunakan field "delivery_location" di mutasi StoreRoomService -> description
3. Untuk baca lokasi pengantaran menggunakan field "delivery_location" di type RoomService -> description

**Comment by chelsymooy** [comment]
query sample


mutation room_service{
  StoreRoomService(reception_id:16 room_id:10 user_id:1 lines:[
    {room_item_id:1262 qty:1}
  ] description:{delivery_location:"POOL"}) {
    id
    description{
      delivery_location
    }
  }
}

**Comment by chelsymooy** [comment]
TEST LOCATION

http://128.199.145.173:9888/graphiql

ACTIVE STAY

username: 6281333517875	
password: 123123123

**Comment by budi7** [comment]
policy guest service:  untuk item "Lainnya" saja

**Comment by budi7** [comment]
updated at https://github.com/budi7/kontena/releases/tag/1.2.1
